/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.github.lgdd.liferay.commerce.after.sales.request.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AfterSalesRequest service. Represents a row in the &quot;DEV24_AfterSalesRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.github.lgdd.liferay.commerce.after.sales.request.model.impl.AfterSalesRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.github.lgdd.liferay.commerce.after.sales.request.model.impl.AfterSalesRequestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AfterSalesRequest
 * @generated
 */
@ProviderType
public interface AfterSalesRequestModel
	extends BaseModel<AfterSalesRequest>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a after sales request model instance should use the {@link AfterSalesRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this after sales request.
	 *
	 * @return the primary key of this after sales request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this after sales request.
	 *
	 * @param primaryKey the primary key of this after sales request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this after sales request.
	 *
	 * @return the uuid of this after sales request
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this after sales request.
	 *
	 * @param uuid the uuid of this after sales request
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the after sales request ID of this after sales request.
	 *
	 * @return the after sales request ID of this after sales request
	 */
	public long getAfterSalesRequestId();

	/**
	 * Sets the after sales request ID of this after sales request.
	 *
	 * @param afterSalesRequestId the after sales request ID of this after sales request
	 */
	public void setAfterSalesRequestId(long afterSalesRequestId);

	/**
	 * Returns the group ID of this after sales request.
	 *
	 * @return the group ID of this after sales request
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this after sales request.
	 *
	 * @param groupId the group ID of this after sales request
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this after sales request.
	 *
	 * @return the company ID of this after sales request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this after sales request.
	 *
	 * @param companyId the company ID of this after sales request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this after sales request.
	 *
	 * @return the user ID of this after sales request
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this after sales request.
	 *
	 * @param userId the user ID of this after sales request
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this after sales request.
	 *
	 * @return the user uuid of this after sales request
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this after sales request.
	 *
	 * @param userUuid the user uuid of this after sales request
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this after sales request.
	 *
	 * @return the user name of this after sales request
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this after sales request.
	 *
	 * @param userName the user name of this after sales request
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this after sales request.
	 *
	 * @return the create date of this after sales request
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this after sales request.
	 *
	 * @param createDate the create date of this after sales request
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this after sales request.
	 *
	 * @return the modified date of this after sales request
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this after sales request.
	 *
	 * @param modifiedDate the modified date of this after sales request
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this after sales request.
	 *
	 * @return the status of this after sales request
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this after sales request.
	 *
	 * @param status the status of this after sales request
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this after sales request.
	 *
	 * @return the status by user ID of this after sales request
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this after sales request.
	 *
	 * @param statusByUserId the status by user ID of this after sales request
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this after sales request.
	 *
	 * @return the status by user uuid of this after sales request
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this after sales request.
	 *
	 * @param statusByUserUuid the status by user uuid of this after sales request
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this after sales request.
	 *
	 * @return the status by user name of this after sales request
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this after sales request.
	 *
	 * @param statusByUserName the status by user name of this after sales request
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this after sales request.
	 *
	 * @return the status date of this after sales request
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this after sales request.
	 *
	 * @param statusDate the status date of this after sales request
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the title of this after sales request.
	 *
	 * @return the title of this after sales request
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this after sales request.
	 *
	 * @param title the title of this after sales request
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this after sales request.
	 *
	 * @return the description of this after sales request
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this after sales request.
	 *
	 * @param description the description of this after sales request
	 */
	public void setDescription(String description);

	/**
	 * Returns <code>true</code> if this after sales request is approved.
	 *
	 * @return <code>true</code> if this after sales request is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this after sales request is denied.
	 *
	 * @return <code>true</code> if this after sales request is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this after sales request is a draft.
	 *
	 * @return <code>true</code> if this after sales request is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this after sales request is expired.
	 *
	 * @return <code>true</code> if this after sales request is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this after sales request is inactive.
	 *
	 * @return <code>true</code> if this after sales request is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this after sales request is incomplete.
	 *
	 * @return <code>true</code> if this after sales request is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this after sales request is pending.
	 *
	 * @return <code>true</code> if this after sales request is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this after sales request is scheduled.
	 *
	 * @return <code>true</code> if this after sales request is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public AfterSalesRequest cloneWithOriginalValues();

}